### ISSUE TITLE
Crashing on Log

### ISSUE THREAD

**Issue by Maxattax97** [Evidlo/imgurt#1]
Hey, I have noticed that redrum crashes a lot with this error if I just run `redrum`...

```
Found cache at /home/max/.cache/redrum_cache.json
Traceback (most recent call last):
  File "/home/max/.local/bin//redrum", line 33, in <module>
    sys.exit(load_entry_point('redrum==1.5.2', 'console_scripts', 'redrum')())
  File "/home/max/.local/lib/python3.10/site-packages/redrum/redrum.py", line 322, in main
    image = weighted_select(config, images, seen)
  File "/home/max/.local/lib/python3.10/site-packages/redrum/redrum.py", line 176, in weighted_select
    image['subreddit'],
KeyError: 'subreddit'
```

Looks like this print is offending:
```
    print("Selected {0} ({1}) with score {2} out of {3} images".format(image['link'],
                                                                       image['subreddit'],
                                                                       image['redrum_score'],
                                                                       len(images)))
```

If I comment it out, everything seems hunky-dory.

Here is my config:
```
[redrum]

## search for images with this aspect ratio and resolution
screen_width = 3440
screen_height = 1440

##---------- Image Searching ----------

## search these subreddits
subreddits = cityporn
             earthporn
             infrastructureporn
             roomporn
             skyporn
             villageporn
             natureporn
             jungleporn
             breathless
             amateurearthporn
             bridgeporn
             summerporn
             architectureporn
#             winterporn
#             earthporn
#             natureporn
#             spaceporn
#             jungleporn
#             astrophotography
#             californiapics
#             breathless
#             amateurphotography
#             amateurearthporn
#             eyecandy
#             bridgeporn
#             cabinporn
#             churchporn
#             megalithporn
#             summerporn
#             architectureporn


## show nsfw images
sfw_only = True

## allow selecting previously selected images
# unseen_only = False

##---------- Image Ranking ----------
##
## Images are scored as follows:
##
## 1. Calculate 3 input scores for each image
##
##    pixel_score = [total image pixels] / [total screen pixels]
##
##    ratio_score = [image x-y ratio] / [screen x-y ratio]
##                                    or
##                  [screen x-y ratio] / [image x-y ratio]
##                             (whichever is <1)
##
##    views_score = [# views of this image] / [highest # views of all images]
##
## 2. Run each input score through a logistic function to get 3 logistic scores per image.
##    See https://en.wikipedia.org/wiki/Logistic_function
##
##                         1 -  -  -  -  -  -  ‚------
##                                            /
##       logistic score   .5 -  -  -  -  -  -/ <-- midpoint with slope k
##                                          /
##                         0 -  -  - ------‘
##
##                                     input score
##
##    Logistic functions are defined by their midpoint and slope (k).  Set the midpoint
##    to the threshold between a good and bad input score.
##    eg. if an image having 60% of the pixels of the screen is unacceptable
##        but 90% is acceptable, set pixel_midpoint to .75
##    Use k to control the slope or steepness at the midpoint to define a harder boundary
##    between good and bad input score.
##
## 3. Multiply logistic scores to get a final score for each image.
##
##    final_score = ratio_logistic_score * views_logistic_score * pixel_logistic_score

## images with a x-y ratio within 5% of the screen ratio will get a ratio score
## of .5 or higher
# ratio_midpoint = .95
# ratio_k = 15

## setting views_midpoint to .75 will give images whose number of views is in the 75th
## percentile a views score of .5, a higher views score for more views and vice versa
# views_midpoint = .75
# views_k = 2

## setting pixel_midpoint to 1 with large pixel_k will essentially
## filter out images with lower pixel count than the screen
# pixel_midpoint = 1
pixel_k = 100


#---------- Caching / Downloading ----------

## where to store image metadata and score
cache_file = ~/.cache/redrum_cache.json

## imgur api client id
client_id = ba4c0410bfae2a0

#-------------- Set Wallpaper --------------

## XFCE
# wallpaper_command = xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitor0/image-path --reset;xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitor0/image-path --set {image_file}

## Gnome
# gsettings set org.gnome.desktop.background picture-uri 'file://{image_file}'

## other
# wallpaper_command = feh --bg-fill {image_file}
wallpaper_command = nitrogen --save --set-zoom-fill {image_file}
```

**Comment by Evidlo** [comment]
Sorry I didn't reply sooner.  Do you think you can upload your cache so I can have a look?

**Comment by Maxattax97** [comment]
Here's a gist of it (it's like 5 MB right now):
https://gist.github.com/Maxattax97/99c46d8b3ac1b9e60d0caaf30b54a165

I have been running with the print disabled and it's been fine.

**Comment by Evidlo** [comment]
Two years later...

Fixed in https://github.com/Evidlo/redrum/commit/ca16bfa5fe3f25fce5aaeae5f8cae5022b50c779
